### ISSUE TITLE
Title of CoC section not changed

### ISSUE THREAD

**Issue by vipulgupta2048** [pythonindia/inpycon2018#59]
CoC section still has the old title when Bangalore was the venue for the conference. 
Here is a link to the specific line -https://github.com/pythonindia/inpycon2018/blob/d9796169cab687c8a9ee74dccb220d48a427d230/coc.html#L10

**Comment by ananyo2012** [comment]
@vipulgupta2048 Thanks for pointing this out. We will update this. 

@chirag200666 @realslimshanky Do you think we should recreate the website using a static website generator like jekyll or pelican since these things are really becoming redundant? Since the content is not too large migrating shouldn't be difficult.

**Comment by vipulgupta2048** [comment]
I can/want to help with that, I used to work on the same structure back in PyCon 2017. Would love to contribute more.

**Comment by realslimshanky** [comment]
@vipulgupta2048 it has already been fixed in #60
